// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: order.proto

package order_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackType int32

const (
	PackType_without PackType = 0
	PackType_bag     PackType = 1
	PackType_box     PackType = 2
	PackType_film    PackType = 3
)

// Enum value maps for PackType.
var (
	PackType_name = map[int32]string{
		0: "without",
		1: "bag",
		2: "box",
		3: "film",
	}
	PackType_value = map[string]int32{
		"without": 0,
		"bag":     1,
		"box":     2,
		"film":    3,
	}
)

func (x PackType) Enum() *PackType {
	p := new(PackType)
	*p = x
	return p
}

func (x PackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (PackType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x PackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackType.Descriptor instead.
func (PackType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type OrderStatus int32

const (
	OrderStatus_delivered OrderStatus = 0
	OrderStatus_accepted  OrderStatus = 1
	OrderStatus_returned  OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "delivered",
		1: "accepted",
		2: "returned",
	}
	OrderStatus_value = map[string]int32{
		"delivered": 0,
		"accepted":  1,
		"returned":  2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type Operation int32

const (
	Operation_return Operation = 0
	Operation_issue  Operation = 1
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "return",
		1: "issue",
	}
	Operation_value = map[string]int32{
		"return": 0,
		"issue":  1,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[2].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[2]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

type Pack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packtype      PackType               `protobuf:"varint,1,opt,name=packtype,proto3,enum=order_v1.PackType" json:"packtype,omitempty"`
	Extrapack     *PackType              `protobuf:"varint,2,opt,name=extrapack,proto3,enum=order_v1.PackType,oneof" json:"extrapack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pack) Reset() {
	*x = Pack{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Pack) GetPacktype() PackType {
	if x != nil {
		return x.Packtype
	}
	return PackType_without
}

func (x *Pack) GetExtrapack() PackType {
	if x != nil && x.Extrapack != nil {
		return *x.Extrapack
	}
	return PackType_without
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orderid       int64                  `protobuf:"varint,1,opt,name=orderid,proto3" json:"orderid,omitempty"`
	Userid        int64                  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Weight        int64                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Packaging     *Pack                  `protobuf:"bytes,5,opt,name=packaging,proto3" json:"packaging,omitempty"`
	Instoragefrom *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=instoragefrom,proto3" json:"instoragefrom,omitempty"`
	Shelflife     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=shelflife,proto3" json:"shelflife,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Twodaysoflife *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=twodaysoflife,proto3" json:"twodaysoflife,omitempty"`
	Lastupdate    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=lastupdate,proto3" json:"lastupdate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetOrderid() int64 {
	if x != nil {
		return x.Orderid
	}
	return 0
}

func (x *Order) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Order) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Order) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetPackaging() *Pack {
	if x != nil {
		return x.Packaging
	}
	return nil
}

func (x *Order) GetInstoragefrom() *timestamppb.Timestamp {
	if x != nil {
		return x.Instoragefrom
	}
	return nil
}

func (x *Order) GetShelflife() *timestamppb.Timestamp {
	if x != nil {
		return x.Shelflife
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTwodaysoflife() *timestamppb.Timestamp {
	if x != nil {
		return x.Twodaysoflife
	}
	return nil
}

func (x *Order) GetLastupdate() *timestamppb.Timestamp {
	if x != nil {
		return x.Lastupdate
	}
	return nil
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Weight        int64                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PackType      PackType               `protobuf:"varint,5,opt,name=pack_type,json=packType,proto3,enum=order_v1.PackType" json:"pack_type,omitempty"`
	ExtraPack     *PackType              `protobuf:"varint,6,opt,name=extra_pack,json=extraPack,proto3,enum=order_v1.PackType,oneof" json:"extra_pack,omitempty"`
	ShelfLife     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=shelf_life,json=shelfLife,proto3" json:"shelf_life,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AcceptRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AcceptRequest) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AcceptRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AcceptRequest) GetPackType() PackType {
	if x != nil {
		return x.PackType
	}
	return PackType_without
}

func (x *AcceptRequest) GetExtraPack() PackType {
	if x != nil && x.ExtraPack != nil {
		return *x.ExtraPack
	}
	return PackType_without
}

func (x *AcceptRequest) GetShelfLife() *timestamppb.Timestamp {
	if x != nil {
		return x.ShelfLife
	}
	return nil
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BulkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRequest) Reset() {
	*x = BulkRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRequest) ProtoMessage() {}

func (x *BulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRequest.ProtoReflect.Descriptor instead.
func (*BulkRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *BulkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BulkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkResponse) Reset() {
	*x = BulkResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResponse) ProtoMessage() {}

func (x *BulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResponse.ProtoReflect.Descriptor instead.
func (*BulkResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *BulkResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryResponse) Reset() {
	*x = ListHistoryResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryResponse) ProtoMessage() {}

func (x *ListHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListHistoryResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ListOrdersUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	N             *int64                 `protobuf:"varint,2,opt,name=n,proto3,oneof" json:"n,omitempty"`
	InPvz         *bool                  `protobuf:"varint,3,opt,name=in_pvz,json=inPvz,proto3,oneof" json:"in_pvz,omitempty"`
	Limit         *int64                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Page          *int64                 `protobuf:"varint,5,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Pag           *bool                  `protobuf:"varint,6,opt,name=pag,proto3,oneof" json:"pag,omitempty"`
	Finder        *bool                  `protobuf:"varint,7,opt,name=finder,proto3,oneof" json:"finder,omitempty"`
	OrderFinder   *string                `protobuf:"bytes,8,opt,name=order_finder,json=orderFinder,proto3,oneof" json:"order_finder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersUserRequest) Reset() {
	*x = ListOrdersUserRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersUserRequest) ProtoMessage() {}

func (x *ListOrdersUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersUserRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersUserRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersUserRequest) GetN() int64 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

func (x *ListOrdersUserRequest) GetInPvz() bool {
	if x != nil && x.InPvz != nil {
		return *x.InPvz
	}
	return false
}

func (x *ListOrdersUserRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListOrdersUserRequest) GetPage() int64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListOrdersUserRequest) GetPag() bool {
	if x != nil && x.Pag != nil {
		return *x.Pag
	}
	return false
}

func (x *ListOrdersUserRequest) GetFinder() bool {
	if x != nil && x.Finder != nil {
		return *x.Finder
	}
	return false
}

func (x *ListOrdersUserRequest) GetOrderFinder() string {
	if x != nil && x.OrderFinder != nil {
		return *x.OrderFinder
	}
	return ""
}

type ListOrdersUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersUserResponse) Reset() {
	*x = ListOrdersUserResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersUserResponse) ProtoMessage() {}

func (x *ListOrdersUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersUserResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersUserResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersUserResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ListReturnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int64                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Page          *int64                 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Finder        *bool                  `protobuf:"varint,3,opt,name=finder,proto3,oneof" json:"finder,omitempty"`
	OrderFinder   *string                `protobuf:"bytes,4,opt,name=order_finder,json=orderFinder,proto3,oneof" json:"order_finder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReturnsRequest) Reset() {
	*x = ListReturnsRequest{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReturnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReturnsRequest) ProtoMessage() {}

func (x *ListReturnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReturnsRequest.ProtoReflect.Descriptor instead.
func (*ListReturnsRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *ListReturnsRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListReturnsRequest) GetPage() int64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListReturnsRequest) GetFinder() bool {
	if x != nil && x.Finder != nil {
		return *x.Finder
	}
	return false
}

func (x *ListReturnsRequest) GetOrderFinder() string {
	if x != nil && x.OrderFinder != nil {
		return *x.OrderFinder
	}
	return ""
}

type ListReturnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Returns       []*Order               `protobuf:"bytes,2,rep,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReturnsResponse) Reset() {
	*x = ListReturnsResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReturnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReturnsResponse) ProtoMessage() {}

func (x *ListReturnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReturnsResponse.ProtoReflect.Descriptor instead.
func (*ListReturnsResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *ListReturnsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListReturnsResponse) GetReturns() []*Order {
	if x != nil {
		return x.Returns
	}
	return nil
}

type ProcessClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Operation     Operation              `protobuf:"varint,2,opt,name=operation,proto3,enum=order_v1.Operation" json:"operation,omitempty"`
	OrderIds      []int64                `protobuf:"varint,3,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessClientRequest) Reset() {
	*x = ProcessClientRequest{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessClientRequest) ProtoMessage() {}

func (x *ProcessClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessClientRequest.ProtoReflect.Descriptor instead.
func (*ProcessClientRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessClientRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProcessClientRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_return
}

func (x *ProcessClientRequest) GetOrderIds() []int64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type ProcessClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderIds      []int64                `protobuf:"varint,1,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessClientResponse) Reset() {
	*x = ProcessClientResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessClientResponse) ProtoMessage() {}

func (x *ProcessClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessClientResponse.ProtoReflect.Descriptor instead.
func (*ProcessClientResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessClientResponse) GetOrderIds() []int64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type ReturnOrderToCourierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnOrderToCourierRequest) Reset() {
	*x = ReturnOrderToCourierRequest{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnOrderToCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnOrderToCourierRequest) ProtoMessage() {}

func (x *ReturnOrderToCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnOrderToCourierRequest.ProtoReflect.Descriptor instead.
func (*ReturnOrderToCourierRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *ReturnOrderToCourierRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ReturnOrderToCourierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnOrderToCourierResponse) Reset() {
	*x = ReturnOrderToCourierResponse{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnOrderToCourierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnOrderToCourierResponse) ProtoMessage() {}

func (x *ReturnOrderToCourierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnOrderToCourierResponse.ProtoReflect.Descriptor instead.
func (*ReturnOrderToCourierResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *ReturnOrderToCourierResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\border_v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"{\n" +
	"\x04Pack\x12.\n" +
	"\bpacktype\x18\x01 \x01(\x0e2\x12.order_v1.PackTypeR\bpacktype\x125\n" +
	"\textrapack\x18\x02 \x01(\x0e2\x12.order_v1.PackTypeH\x00R\textrapack\x88\x01\x01B\f\n" +
	"\n" +
	"_extrapack\"\xa7\x03\n" +
	"\x05Order\x12\x18\n" +
	"\aorderid\x18\x01 \x01(\x03R\aorderid\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\x03R\x06userid\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x03R\x06weight\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12,\n" +
	"\tpackaging\x18\x05 \x01(\v2\x0e.order_v1.PackR\tpackaging\x12@\n" +
	"\rinstoragefrom\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rinstoragefrom\x128\n" +
	"\tshelflife\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tshelflife\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12@\n" +
	"\rtwodaysoflife\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rtwodaysoflife\x12:\n" +
	"\n" +
	"lastupdate\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastupdate\"\xa4\x02\n" +
	"\rAcceptRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x03R\x06weight\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12/\n" +
	"\tpack_type\x18\x05 \x01(\x0e2\x12.order_v1.PackTypeR\bpackType\x126\n" +
	"\n" +
	"extra_pack\x18\x06 \x01(\x0e2\x12.order_v1.PackTypeH\x00R\textraPack\x88\x01\x01\x129\n" +
	"\n" +
	"shelf_life\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tshelfLifeB\r\n" +
	"\v_extra_pack\"*\n" +
	"\x0eAcceptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\vBulkRequest\x12\x12\n" +
	"\x04Path\x18\x01 \x01(\tR\x04Path\"$\n" +
	"\fBulkResponse\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x03R\x05Count\">\n" +
	"\x13ListHistoryResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order_v1.OrderR\x06orders\"\xb7\x02\n" +
	"\x15ListOrdersUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x11\n" +
	"\x01n\x18\x02 \x01(\x03H\x00R\x01n\x88\x01\x01\x12\x1a\n" +
	"\x06in_pvz\x18\x03 \x01(\bH\x01R\x05inPvz\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x03H\x02R\x05limit\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x05 \x01(\x03H\x03R\x04page\x88\x01\x01\x12\x15\n" +
	"\x03pag\x18\x06 \x01(\bH\x04R\x03pag\x88\x01\x01\x12\x1b\n" +
	"\x06finder\x18\a \x01(\bH\x05R\x06finder\x88\x01\x01\x12&\n" +
	"\forder_finder\x18\b \x01(\tH\x06R\vorderFinder\x88\x01\x01B\x04\n" +
	"\x02_nB\t\n" +
	"\a_in_pvzB\b\n" +
	"\x06_limitB\a\n" +
	"\x05_pageB\x06\n" +
	"\x04_pagB\t\n" +
	"\a_finderB\x0f\n" +
	"\r_order_finder\"A\n" +
	"\x16ListOrdersUserResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order_v1.OrderR\x06orders\"\xbc\x01\n" +
	"\x12ListReturnsRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x03H\x01R\x04page\x88\x01\x01\x12\x1b\n" +
	"\x06finder\x18\x03 \x01(\bH\x02R\x06finder\x88\x01\x01\x12&\n" +
	"\forder_finder\x18\x04 \x01(\tH\x03R\vorderFinder\x88\x01\x01B\b\n" +
	"\x06_limitB\a\n" +
	"\x05_pageB\t\n" +
	"\a_finderB\x0f\n" +
	"\r_order_finder\"V\n" +
	"\x13ListReturnsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12)\n" +
	"\areturns\x18\x02 \x03(\v2\x0f.order_v1.OrderR\areturns\"\x7f\n" +
	"\x14ProcessClientRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x121\n" +
	"\toperation\x18\x02 \x01(\x0e2\x13.order_v1.OperationR\toperation\x12\x1b\n" +
	"\torder_ids\x18\x03 \x03(\x03R\borderIds\"4\n" +
	"\x15ProcessClientResponse\x12\x1b\n" +
	"\torder_ids\x18\x01 \x03(\x03R\borderIds\"8\n" +
	"\x1bReturnOrderToCourierRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"8\n" +
	"\x1cReturnOrderToCourierResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*3\n" +
	"\bPackType\x12\v\n" +
	"\awithout\x10\x00\x12\a\n" +
	"\x03bag\x10\x01\x12\a\n" +
	"\x03box\x10\x02\x12\b\n" +
	"\x04film\x10\x03*8\n" +
	"\vOrderStatus\x12\r\n" +
	"\tdelivered\x10\x00\x12\f\n" +
	"\baccepted\x10\x01\x12\f\n" +
	"\breturned\x10\x02*\"\n" +
	"\tOperation\x12\n" +
	"\n" +
	"\x06return\x10\x00\x12\t\n" +
	"\x05issue\x10\x012\xae\x04\n" +
	"\aOrderV1\x12@\n" +
	"\vAcceptOrder\x12\x17.order_v1.AcceptRequest\x1a\x18.order_v1.AcceptResponse\x12A\n" +
	"\x10BulkAcceptOrders\x12\x15.order_v1.BulkRequest\x1a\x16.order_v1.BulkResponse\x12D\n" +
	"\vListHistory\x12\x16.google.protobuf.Empty\x1a\x1d.order_v1.ListHistoryResponse\x12S\n" +
	"\x0eListOrdersUser\x12\x1f.order_v1.ListOrdersUserRequest\x1a .order_v1.ListOrdersUserResponse\x12J\n" +
	"\vListReturns\x12\x1c.order_v1.ListReturnsRequest\x1a\x1d.order_v1.ListReturnsResponse\x12P\n" +
	"\rProcessClient\x12\x1e.order_v1.ProcessClientRequest\x1a\x1f.order_v1.ProcessClientResponse\x12e\n" +
	"\x14ReturnOrderToCourier\x12%.order_v1.ReturnOrderToCourierRequest\x1a&.order_v1.ReturnOrderToCourierResponseB4Z2github.com/KrllF/pvz_service/pkg/order_v1;order_v1b\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_order_proto_goTypes = []any{
	(PackType)(0),                        // 0: order_v1.PackType
	(OrderStatus)(0),                     // 1: order_v1.OrderStatus
	(Operation)(0),                       // 2: order_v1.Operation
	(*Pack)(nil),                         // 3: order_v1.Pack
	(*Order)(nil),                        // 4: order_v1.Order
	(*AcceptRequest)(nil),                // 5: order_v1.AcceptRequest
	(*AcceptResponse)(nil),               // 6: order_v1.AcceptResponse
	(*BulkRequest)(nil),                  // 7: order_v1.BulkRequest
	(*BulkResponse)(nil),                 // 8: order_v1.BulkResponse
	(*ListHistoryResponse)(nil),          // 9: order_v1.ListHistoryResponse
	(*ListOrdersUserRequest)(nil),        // 10: order_v1.ListOrdersUserRequest
	(*ListOrdersUserResponse)(nil),       // 11: order_v1.ListOrdersUserResponse
	(*ListReturnsRequest)(nil),           // 12: order_v1.ListReturnsRequest
	(*ListReturnsResponse)(nil),          // 13: order_v1.ListReturnsResponse
	(*ProcessClientRequest)(nil),         // 14: order_v1.ProcessClientRequest
	(*ProcessClientResponse)(nil),        // 15: order_v1.ProcessClientResponse
	(*ReturnOrderToCourierRequest)(nil),  // 16: order_v1.ReturnOrderToCourierRequest
	(*ReturnOrderToCourierResponse)(nil), // 17: order_v1.ReturnOrderToCourierResponse
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 19: google.protobuf.Empty
}
var file_order_proto_depIdxs = []int32{
	0,  // 0: order_v1.Pack.packtype:type_name -> order_v1.PackType
	0,  // 1: order_v1.Pack.extrapack:type_name -> order_v1.PackType
	3,  // 2: order_v1.Order.packaging:type_name -> order_v1.Pack
	18, // 3: order_v1.Order.instoragefrom:type_name -> google.protobuf.Timestamp
	18, // 4: order_v1.Order.shelflife:type_name -> google.protobuf.Timestamp
	18, // 5: order_v1.Order.twodaysoflife:type_name -> google.protobuf.Timestamp
	18, // 6: order_v1.Order.lastupdate:type_name -> google.protobuf.Timestamp
	0,  // 7: order_v1.AcceptRequest.pack_type:type_name -> order_v1.PackType
	0,  // 8: order_v1.AcceptRequest.extra_pack:type_name -> order_v1.PackType
	18, // 9: order_v1.AcceptRequest.shelf_life:type_name -> google.protobuf.Timestamp
	4,  // 10: order_v1.ListHistoryResponse.orders:type_name -> order_v1.Order
	4,  // 11: order_v1.ListOrdersUserResponse.orders:type_name -> order_v1.Order
	4,  // 12: order_v1.ListReturnsResponse.returns:type_name -> order_v1.Order
	2,  // 13: order_v1.ProcessClientRequest.operation:type_name -> order_v1.Operation
	5,  // 14: order_v1.OrderV1.AcceptOrder:input_type -> order_v1.AcceptRequest
	7,  // 15: order_v1.OrderV1.BulkAcceptOrders:input_type -> order_v1.BulkRequest
	19, // 16: order_v1.OrderV1.ListHistory:input_type -> google.protobuf.Empty
	10, // 17: order_v1.OrderV1.ListOrdersUser:input_type -> order_v1.ListOrdersUserRequest
	12, // 18: order_v1.OrderV1.ListReturns:input_type -> order_v1.ListReturnsRequest
	14, // 19: order_v1.OrderV1.ProcessClient:input_type -> order_v1.ProcessClientRequest
	16, // 20: order_v1.OrderV1.ReturnOrderToCourier:input_type -> order_v1.ReturnOrderToCourierRequest
	6,  // 21: order_v1.OrderV1.AcceptOrder:output_type -> order_v1.AcceptResponse
	8,  // 22: order_v1.OrderV1.BulkAcceptOrders:output_type -> order_v1.BulkResponse
	9,  // 23: order_v1.OrderV1.ListHistory:output_type -> order_v1.ListHistoryResponse
	11, // 24: order_v1.OrderV1.ListOrdersUser:output_type -> order_v1.ListOrdersUserResponse
	13, // 25: order_v1.OrderV1.ListReturns:output_type -> order_v1.ListReturnsResponse
	15, // 26: order_v1.OrderV1.ProcessClient:output_type -> order_v1.ProcessClientResponse
	17, // 27: order_v1.OrderV1.ReturnOrderToCourier:output_type -> order_v1.ReturnOrderToCourierResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_order_proto_msgTypes[0].OneofWrappers = []any{}
	file_order_proto_msgTypes[2].OneofWrappers = []any{}
	file_order_proto_msgTypes[7].OneofWrappers = []any{}
	file_order_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
