// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: order.proto

package order_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderV1_AcceptOrder_FullMethodName          = "/order_v1.OrderV1/AcceptOrder"
	OrderV1_BulkAcceptOrders_FullMethodName     = "/order_v1.OrderV1/BulkAcceptOrders"
	OrderV1_ListHistory_FullMethodName          = "/order_v1.OrderV1/ListHistory"
	OrderV1_ListOrdersUser_FullMethodName       = "/order_v1.OrderV1/ListOrdersUser"
	OrderV1_ListReturns_FullMethodName          = "/order_v1.OrderV1/ListReturns"
	OrderV1_ProcessClient_FullMethodName        = "/order_v1.OrderV1/ProcessClient"
	OrderV1_ReturnOrderToCourier_FullMethodName = "/order_v1.OrderV1/ReturnOrderToCourier"
)

// OrderV1Client is the client API for OrderV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderV1Client interface {
	AcceptOrder(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error)
	BulkAcceptOrders(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error)
	ListHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListHistoryResponse, error)
	ListOrdersUser(ctx context.Context, in *ListOrdersUserRequest, opts ...grpc.CallOption) (*ListOrdersUserResponse, error)
	ListReturns(ctx context.Context, in *ListReturnsRequest, opts ...grpc.CallOption) (*ListReturnsResponse, error)
	ProcessClient(ctx context.Context, in *ProcessClientRequest, opts ...grpc.CallOption) (*ProcessClientResponse, error)
	ReturnOrderToCourier(ctx context.Context, in *ReturnOrderToCourierRequest, opts ...grpc.CallOption) (*ReturnOrderToCourierResponse, error)
}

type orderV1Client struct {
	cc grpc.ClientConnInterface
}

func NewOrderV1Client(cc grpc.ClientConnInterface) OrderV1Client {
	return &orderV1Client{cc}
}

func (c *orderV1Client) AcceptOrder(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptResponse)
	err := c.cc.Invoke(ctx, OrderV1_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderV1Client) BulkAcceptOrders(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResponse)
	err := c.cc.Invoke(ctx, OrderV1_BulkAcceptOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderV1Client) ListHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHistoryResponse)
	err := c.cc.Invoke(ctx, OrderV1_ListHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderV1Client) ListOrdersUser(ctx context.Context, in *ListOrdersUserRequest, opts ...grpc.CallOption) (*ListOrdersUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersUserResponse)
	err := c.cc.Invoke(ctx, OrderV1_ListOrdersUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderV1Client) ListReturns(ctx context.Context, in *ListReturnsRequest, opts ...grpc.CallOption) (*ListReturnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReturnsResponse)
	err := c.cc.Invoke(ctx, OrderV1_ListReturns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderV1Client) ProcessClient(ctx context.Context, in *ProcessClientRequest, opts ...grpc.CallOption) (*ProcessClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessClientResponse)
	err := c.cc.Invoke(ctx, OrderV1_ProcessClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderV1Client) ReturnOrderToCourier(ctx context.Context, in *ReturnOrderToCourierRequest, opts ...grpc.CallOption) (*ReturnOrderToCourierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnOrderToCourierResponse)
	err := c.cc.Invoke(ctx, OrderV1_ReturnOrderToCourier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderV1Server is the server API for OrderV1 service.
// All implementations must embed UnimplementedOrderV1Server
// for forward compatibility.
type OrderV1Server interface {
	AcceptOrder(context.Context, *AcceptRequest) (*AcceptResponse, error)
	BulkAcceptOrders(context.Context, *BulkRequest) (*BulkResponse, error)
	ListHistory(context.Context, *emptypb.Empty) (*ListHistoryResponse, error)
	ListOrdersUser(context.Context, *ListOrdersUserRequest) (*ListOrdersUserResponse, error)
	ListReturns(context.Context, *ListReturnsRequest) (*ListReturnsResponse, error)
	ProcessClient(context.Context, *ProcessClientRequest) (*ProcessClientResponse, error)
	ReturnOrderToCourier(context.Context, *ReturnOrderToCourierRequest) (*ReturnOrderToCourierResponse, error)
	mustEmbedUnimplementedOrderV1Server()
}

// UnimplementedOrderV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderV1Server struct{}

func (UnimplementedOrderV1Server) AcceptOrder(context.Context, *AcceptRequest) (*AcceptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedOrderV1Server) BulkAcceptOrders(context.Context, *BulkRequest) (*BulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkAcceptOrders not implemented")
}
func (UnimplementedOrderV1Server) ListHistory(context.Context, *emptypb.Empty) (*ListHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHistory not implemented")
}
func (UnimplementedOrderV1Server) ListOrdersUser(context.Context, *ListOrdersUserRequest) (*ListOrdersUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrdersUser not implemented")
}
func (UnimplementedOrderV1Server) ListReturns(context.Context, *ListReturnsRequest) (*ListReturnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReturns not implemented")
}
func (UnimplementedOrderV1Server) ProcessClient(context.Context, *ProcessClientRequest) (*ProcessClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessClient not implemented")
}
func (UnimplementedOrderV1Server) ReturnOrderToCourier(context.Context, *ReturnOrderToCourierRequest) (*ReturnOrderToCourierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnOrderToCourier not implemented")
}
func (UnimplementedOrderV1Server) mustEmbedUnimplementedOrderV1Server() {}
func (UnimplementedOrderV1Server) testEmbeddedByValue()                 {}

// UnsafeOrderV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderV1Server will
// result in compilation errors.
type UnsafeOrderV1Server interface {
	mustEmbedUnimplementedOrderV1Server()
}

func RegisterOrderV1Server(s grpc.ServiceRegistrar, srv OrderV1Server) {
	// If the following call pancis, it indicates UnimplementedOrderV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderV1_ServiceDesc, srv)
}

func _OrderV1_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderV1Server).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderV1_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderV1Server).AcceptOrder(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderV1_BulkAcceptOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderV1Server).BulkAcceptOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderV1_BulkAcceptOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderV1Server).BulkAcceptOrders(ctx, req.(*BulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderV1_ListHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderV1Server).ListHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderV1_ListHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderV1Server).ListHistory(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderV1_ListOrdersUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderV1Server).ListOrdersUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderV1_ListOrdersUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderV1Server).ListOrdersUser(ctx, req.(*ListOrdersUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderV1_ListReturns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReturnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderV1Server).ListReturns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderV1_ListReturns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderV1Server).ListReturns(ctx, req.(*ListReturnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderV1_ProcessClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderV1Server).ProcessClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderV1_ProcessClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderV1Server).ProcessClient(ctx, req.(*ProcessClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderV1_ReturnOrderToCourier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnOrderToCourierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderV1Server).ReturnOrderToCourier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderV1_ReturnOrderToCourier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderV1Server).ReturnOrderToCourier(ctx, req.(*ReturnOrderToCourierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderV1_ServiceDesc is the grpc.ServiceDesc for OrderV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_v1.OrderV1",
	HandlerType: (*OrderV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptOrder",
			Handler:    _OrderV1_AcceptOrder_Handler,
		},
		{
			MethodName: "BulkAcceptOrders",
			Handler:    _OrderV1_BulkAcceptOrders_Handler,
		},
		{
			MethodName: "ListHistory",
			Handler:    _OrderV1_ListHistory_Handler,
		},
		{
			MethodName: "ListOrdersUser",
			Handler:    _OrderV1_ListOrdersUser_Handler,
		},
		{
			MethodName: "ListReturns",
			Handler:    _OrderV1_ListReturns_Handler,
		},
		{
			MethodName: "ProcessClient",
			Handler:    _OrderV1_ProcessClient_Handler,
		},
		{
			MethodName: "ReturnOrderToCourier",
			Handler:    _OrderV1_ReturnOrderToCourier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
