// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/KrllF/pvz_service/internal/entity"
	models "github.com/KrllF/pvz_service/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAcceptService is a mock of AcceptService interface.
type MockAcceptService struct {
	ctrl     *gomock.Controller
	recorder *MockAcceptServiceMockRecorder
}

// MockAcceptServiceMockRecorder is the mock recorder for MockAcceptService.
type MockAcceptServiceMockRecorder struct {
	mock *MockAcceptService
}

// NewMockAcceptService creates a new mock instance.
func NewMockAcceptService(ctrl *gomock.Controller) *MockAcceptService {
	mock := &MockAcceptService{ctrl: ctrl}
	mock.recorder = &MockAcceptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcceptService) EXPECT() *MockAcceptServiceMockRecorder {
	return m.recorder
}

// AcceptOrder mocks base method.
func (m *MockAcceptService) AcceptOrder(ctx context.Context, req entity.OrderEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptOrder", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptOrder indicates an expected call of AcceptOrder.
func (mr *MockAcceptServiceMockRecorder) AcceptOrder(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptOrder", reflect.TypeOf((*MockAcceptService)(nil).AcceptOrder), ctx, req)
}

// BulkAcceptOrders mocks base method.
func (m *MockAcceptService) BulkAcceptOrders(ctx context.Context, path string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAcceptOrders", ctx, path)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkAcceptOrders indicates an expected call of BulkAcceptOrders.
func (mr *MockAcceptServiceMockRecorder) BulkAcceptOrders(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAcceptOrders", reflect.TypeOf((*MockAcceptService)(nil).BulkAcceptOrders), ctx, path)
}

// ProcessClientIssue mocks base method.
func (m *MockAcceptService) ProcessClientIssue(ctx context.Context, userID int64, orderIDs []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessClientIssue", ctx, userID, orderIDs)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessClientIssue indicates an expected call of ProcessClientIssue.
func (mr *MockAcceptServiceMockRecorder) ProcessClientIssue(ctx, userID, orderIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessClientIssue", reflect.TypeOf((*MockAcceptService)(nil).ProcessClientIssue), ctx, userID, orderIDs)
}

// MockReturnsService is a mock of ReturnsService interface.
type MockReturnsService struct {
	ctrl     *gomock.Controller
	recorder *MockReturnsServiceMockRecorder
}

// MockReturnsServiceMockRecorder is the mock recorder for MockReturnsService.
type MockReturnsServiceMockRecorder struct {
	mock *MockReturnsService
}

// NewMockReturnsService creates a new mock instance.
func NewMockReturnsService(ctrl *gomock.Controller) *MockReturnsService {
	mock := &MockReturnsService{ctrl: ctrl}
	mock.recorder = &MockReturnsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReturnsService) EXPECT() *MockReturnsServiceMockRecorder {
	return m.recorder
}

// ProcessClientReturn mocks base method.
func (m *MockReturnsService) ProcessClientReturn(ctx context.Context, userID int64, orderIDs []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessClientReturn", ctx, userID, orderIDs)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessClientReturn indicates an expected call of ProcessClientReturn.
func (mr *MockReturnsServiceMockRecorder) ProcessClientReturn(ctx, userID, orderIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessClientReturn", reflect.TypeOf((*MockReturnsService)(nil).ProcessClientReturn), ctx, userID, orderIDs)
}

// ReturnOrder mocks base method.
func (m *MockReturnsService) ReturnOrder(ctx context.Context, orderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnOrder", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReturnOrder indicates an expected call of ReturnOrder.
func (mr *MockReturnsServiceMockRecorder) ReturnOrder(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnOrder", reflect.TypeOf((*MockReturnsService)(nil).ReturnOrder), ctx, orderID)
}

// MockShowService is a mock of ShowService interface.
type MockShowService struct {
	ctrl     *gomock.Controller
	recorder *MockShowServiceMockRecorder
}

// MockShowServiceMockRecorder is the mock recorder for MockShowService.
type MockShowServiceMockRecorder struct {
	mock *MockShowService
}

// NewMockShowService creates a new mock instance.
func NewMockShowService(ctrl *gomock.Controller) *MockShowService {
	mock := &MockShowService{ctrl: ctrl}
	mock.recorder = &MockShowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowService) EXPECT() *MockShowServiceMockRecorder {
	return m.recorder
}

// ListHistory mocks base method.
func (m *MockShowService) ListHistory(ctx context.Context) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHistory", ctx)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHistory indicates an expected call of ListHistory.
func (mr *MockShowServiceMockRecorder) ListHistory(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHistory", reflect.TypeOf((*MockShowService)(nil).ListHistory), ctx)
}

// ListOrdersUserAllN mocks base method.
func (m *MockShowService) ListOrdersUserAllN(ctx context.Context, userID, opt, limit, page int64, pag, finder bool, orderFinder string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersUserAllN", ctx, userID, opt, limit, page, pag, finder, orderFinder)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersUserAllN indicates an expected call of ListOrdersUserAllN.
func (mr *MockShowServiceMockRecorder) ListOrdersUserAllN(ctx, userID, opt, limit, page, pag, finder, orderFinder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersUserAllN", reflect.TypeOf((*MockShowService)(nil).ListOrdersUserAllN), ctx, userID, opt, limit, page, pag, finder, orderFinder)
}

// ListOrdersUserPVZ mocks base method.
func (m *MockShowService) ListOrdersUserPVZ(ctx context.Context, userID, limit, page int64, pag, finder bool, orderFinder string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersUserPVZ", ctx, userID, limit, page, pag, finder, orderFinder)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersUserPVZ indicates an expected call of ListOrdersUserPVZ.
func (mr *MockShowServiceMockRecorder) ListOrdersUserPVZ(ctx, userID, limit, page, pag, finder, orderFinder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersUserPVZ", reflect.TypeOf((*MockShowService)(nil).ListOrdersUserPVZ), ctx, userID, limit, page, pag, finder, orderFinder)
}

// ListReturns mocks base method.
func (m *MockShowService) ListReturns(ctx context.Context, limit, page int64, finder bool, orderFinder string) ([]models.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReturns", ctx, limit, page, finder, orderFinder)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReturns indicates an expected call of ListReturns.
func (mr *MockShowServiceMockRecorder) ListReturns(ctx, limit, page, finder, orderFinder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReturns", reflect.TypeOf((*MockShowService)(nil).ListReturns), ctx, limit, page, finder, orderFinder)
}
